/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 43
#define YY_END_OF_BUFFER 44
static yyconst short int yy_acclist[255] =
    {   0,
       44,   42,   43,   41,   43,    1,   42,   43,   25,   42,
       43,   33,   42,   43,   34,   42,   43,   39,   42,   43,
       37,   42,   43,   29,   42,   43,   38,   42,   43,   30,
       42,   43,   40,   42,   43,   14,   23,   42,   43,   27,
       42,   43,   36,   42,   43,   26,   42,   43,   35,   42,
       43,   17,   42,   43,   17,   42,   43,   17,   42,   43,
       17,   42,   43,   17,   42,   43,   17,   42,   43,   17,
       42,   43,   17,   42,   43,   17,   42,   43,   17,   42,
       43,   17,   42,   43,   17,   42,   43,   17,   42,   43,
        1,   14,   23,   22,   32,   28,   31,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   14,   14,   14,   24,
       19,   20,   22,   16,   17,   17,   13,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   16,   17,   17,   17,   17,   17,   17,    4,
       17,   17,   17,   17,   17,   17,   17,   17,   14,   14,
       19,   20,   19,   20,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   10,   17,   16,   18,   17,   17,   17,
       17,   17,   17,    3,   17,   17,    9,   17,   20,   16,
       16,   16,   17,   17,   17,   12,   17,   17,   11,   17,

       17,   17,   17,   19,   16,   16,   17,   17,   17,   12,
       17,   11,   17,   17,   17,   17,   17,   17,   20,   20,
       21,   15,   16,   16,   17,   17,    5,   17,   17,   17,
       17,   17,   19,   19,   15,   15,   17,    8,   17,    5,
        6,   17,    7,   17,    2,   17,    8,    6,    7,    7,
        2,   18,   21,   21
    } ;

static yyconst short int yy_accept[412] =
    {   0,
        1,    1,    1,    2,    4,    6,    9,   12,   15,   18,
       21,   24,   27,   30,   33,   36,   40,   43,   46,   49,
       52,   55,   58,   61,   64,   67,   70,   73,   76,   79,
       82,   85,   88,   91,   92,   92,   92,   92,   92,   92,
       94,   94,   94,   94,   95,   96,   97,   98,   98,   98,
       99,  100,  101,  102,  103,  104,  105,  106,  107,  108,
      109,  110,  111,  112,  113,  114,  115,  116,  117,  118,
      118,  118,  118,  118,  119,  121,  121,  123,  124,  124,
      124,  124,  124,  124,  125,  126,  127,  129,  130,  131,
      132,  133,  134,  135,  136,  137,  138,  139,  140,  141,

      142,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  144,  145,  146,  146,  147,  148,
      149,  150,  152,  153,  154,  155,  156,  157,  158,  159,
      160,  160,  161,  163,  163,  163,  163,  163,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      166,  167,  167,  168,  169,  170,  171,  172,  173,  174,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  177,  178,  178,  179,
      180,  180,  181,  181,  182,  183,  183,  184,  186,  187,
      189,  189,  189,  189,  190,  190,  190,  190,  190,  190,

      190,  190,  190,  190,  190,  190,  190,  191,  192,  193,
      193,  193,  193,  194,  194,  195,  195,  196,  196,  198,
      198,  199,  199,  201,  201,  202,  203,  204,  204,  204,
      204,  204,  204,  204,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  206,  207,  207,  207,  207,  207,  207,
      208,  208,  209,  209,  210,  211,  211,  212,  213,  213,
      213,  213,  213,  213,  213,  214,  215,  216,  217,  218,
      219,  220,  220,  221,  221,  221,  221,  221,  221,  221,
      222,  222,  222,  222,  224,  225,  225,  225,  225,  225,
      225,  226,  226,  227,  227,  229,  229,  230,  230,  230,

      230,  230,  230,  230,  230,  230,  231,  232,  233,  234,
      234,  235,  236,  236,  236,  236,  236,  236,  236,  236,
      237,  237,  237,  237,  237,  238,  238,  240,  241,  241,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  247,
      248,  249,  249,  250,  250,  250,  250,  251,  251,  251,
      251,  251,  251,  251,  252,  252,  252,  252,  252,  252,
      252,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,   16,
       17,   18,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   29,   30,   31,   32,   33,
       28,   34,   35,   36,   37,   38,   39,   40,   41,   28,
        1,    1,    1,    1,    1,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   28,   28,   29,   30,   31,
       32,   33,   28,   34,   35,   36,   37,   38,   39,   40,
       41,   28,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   42,   43,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[44] =
    {   0,
        1,    1,    2,    3,    4,    1,    5,    6,    1,    7,
        1,    8,    1,    9,    1,    3,    3,    3,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   11,   11
    } ;

static yyconst short int yy_base[444] =
    {   0,
        0,    0,  902,  903,  903,  898,    0,  903,  903,  903,
      903,  903,  903,  903,  903,   41,  903,   29,  903,  883,
       57,   93,   16,   29,  865,  864,  866,   35,  862,  872,
      861,  874,  866,  888,   44,   61,  873,   63,  875,  113,
       64,   84,   85,    0,  903,  903,  903,  116,  885,    0,
      852,  863,  864,  859,  846,  859,   56,  849,  848,  847,
      843,   30,  846,  854,  846,  852,   59,  850,   90,   78,
       99,  119,    0,  134,  160,    0,  137,    0,  837,  848,
      839,  850,  865,  855,  843,  828,    0,  854,  828,  839,
      831,  832,  819,  821,  813,  826,  823,  822,   61,  807,

      809,  123,  828,  836,  149,  104,  826,  805,  801,  813,
      115,  797,  795,  818,  129,  806,  818,  789,  106,  788,
      131,    0,  787,  785,  123,  797,  136,  794,  790,  150,
      140,  170,  176,  806,  182,  185,  188,  197,  788,  184,
      207,  782,  784,  781,  781,  209,  798,  793,  792,  772,
      771,  245,  774,  206,  756,  210,  755,  767,  751,    0,
      767,  769,  220,  210,  218,  235,  219,  242,  245,  211,
      779,  747,  750,  748,  770,  247,  265,  765,  152,  217,
      750,  155,  262,  727,  191,  267,  726,    0,  296,    0,
      266,  272,    0,  281,  749,  751,  287,  280,  302,  304,

      761,  306,  744,  736,  739,  308,  314,  328,  329,  293,
      323,  237,  738,  299,  722,  735,  722,  709,    0,  346,
      718,  705,    0,  352,  388,  421,  722,  739,  331,  729,
      332,  371,    0,  364,  342,  378,  392,  713,  707,  706,
      701,  712,  398,  399,  423,  696,  701,  339,  713,  334,
      697,  695,  697,  702,  903,  693,  687,  903,  239,  242,
      337,  419,  413,  400,    0,  685,  696,  170,  695,  679,
      367,  708,  448,  707,  409,  697,  442,  430,  424,  383,
      454,  689,  674,  456,  464,  680,  667,  663,  671,  677,
      667,  663,  664,  667,    0,  651,  654,  444,  452,  467,

      466,  470,  468,  465,  662,  474,  648,  336,  477,  678,
      478,  503,  495,  505,  479,  509,  679,  512,  517,  671,
      653,  667,  641,  642,  644,  635,    0,  903,  498,    0,
      523,  492,  520,  521,  526,  529,  628,  531,    0,  532,
      545,  660,  653,  537,  559,  647,  618,  627,    0,  903,
      903,  533,  504,  535,  542,  534,  903,  469,  554,  646,
      568,  641,  634,  903,  560,  551,  569,  595,  580,  590,
      575,  596,  577,  579,  581,  572,  547,  519,  584,  586,
      588,  467,  423,  408,  594,  595,  596,  369,  369,  356,
      361,  320,  310,  250,  244,  210,  604,  598,  614,  619,

      621,  630,  623,  624,  625,  631,  637,  639,  640,  903,
      233,  650,  659,  666,  669,  678,  104,   98,  682,  689,
      697,  706,  711,  719,  728,  737,  743,  751,  760,  769,
      778,   62,  787,  796,  805,  812,   46,  821,  828,  837,
      846,  851,  857
    } ;

static yyconst short int yy_def[444] =
    {   0,
      410,    1,  410,  410,  410,  410,  411,  410,  410,  410,
      410,  410,  410,  410,  410,  412,  410,  410,  410,  410,
      413,  413,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,  410,  414,  410,  410,  410,  410,  412,
      410,  410,  410,  415,  410,  410,  410,  410,  416,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,  410,  414,
      410,  410,  417,  410,  410,  418,  410,  415,  410,  410,
      410,  410,  416,  419,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,  420,  410,  421,  410,  422,  410,  410,  410,  410,
      410,  410,  410,  419,   22,   22,  423,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,  410,
      420,  410,  410,  421,  422,  410,  424,  410,  410,  425,
      410,  410,  410,  410,  410,  410,  426,  410,  427,   22,
       22,  410,   22,   22,   22,   22,   22,   22,   22,   22,
      410,  410,  410,  410,  410,  424,  425,  410,  428,  410,
      429,  410,  410,  410,  426,  430,  410,  427,   22,   22,
      410,   22,  152,   22,   22,  183,   22,   22,  431,   22,
      410,  410,  432,  410,  410,  410,  410,  410,  410,  428,

      429,  433,  410,  410,  410,  410,  430,  430,  430,  410,
      410,  152,   22,  152,   22,  410,   22,  410,   22,  410,
       22,  410,   22,  434,  435,  435,  226,  436,  410,  410,
      410,  410,  437,  410,  433,  433,  433,  410,  410,  410,
      410,  410,  430,  430,  410,  410,  410,  410,  410,   22,
      410,   22,  410,   22,  410,  410,   22,  410,  438,  438,
      438,  438,  438,  152,  226,  226,  226,  226,  226,  226,
      410,  436,  410,  439,  410,  410,  433,  433,  410,  410,
      410,  410,  410,  430,  430,  410,  410,  410,  410,  410,
       22,  410,   22,  410,   22,  410,   22,  410,  438,  438,

      438,  438,  438,  438,  410,  226,  226,  226,  410,  439,
      410,  433,  433,  410,  410,  410,  440,  410,  410,  410,
      410,  410,  410,  410,   22,  410,   22,  410,  410,   22,
      438,  438,  438,  438,  438,  438,  410,  264,  226,  410,
      410,  440,  441,  410,  410,  442,  410,  410,   22,  410,
      410,  410,  438,  438,  438,  438,  410,  410,  410,  441,
      410,  410,  443,  410,  438,  438,  438,  410,  410,  410,
      410,  443,  438,  438,  438,  410,  410,  410,  438,  438,
      438,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,    0,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410
    } ;

static yyconst short int yy_nxt[947] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   22,   25,   26,   22,   27,   22,   22,   28,
       22,   29,   22,   22,   30,   22,   31,   32,   33,   22,
       22,    7,    7,   36,   37,   45,   46,   55,   69,   56,
       38,   57,   39,   62,   40,  274,   41,   42,   43,   48,
       37,   63,   58,   36,   85,   72,   49,   73,   76,   88,
       38,  228,   41,   42,   43,   51,   74,   77,   52,  127,
       71,   71,   69,   86,   91,   69,   69,  100,   76,   76,
       92,   53,   36,   85,   54,   48,   37,   77,   77,   38,

       71,   71,   49,   76,   73,   73,  135,  104,   41,   42,
       43,   51,   77,  102,   52,   36,   37,  136,   48,   69,
       69,   72,   38,   73,   39,   49,   40,  130,   41,   42,
       43,  146,   74,  152,   79,  142,   36,   80,  147,  105,
       85,  150,   81,   38,  130,  103,  106,   74,  107,  143,
       77,  105,   36,   82,  212,  108,  156,  116,  106,   38,
       73,   73,   36,   37,  130,  130,  153,  108,  109,   38,
       85,  158,   36,   75,  217,   41,   42,   43,  105,   38,
      109,  130,  130,  132,  135,  106,  167,  213,  161,   85,
      306,  161,  307,  220,  108,  136,  162,  168,  136,  105,

      163,  164,  165,  163,  164,  165,  106,  109,  183,  170,
      138,  146,  186,  170,  193,  108,  171,  221,  147,  214,
      171,  167,  193,  194,  193,  184,  191,   79,  109,  187,
       80,  194,  168,  194,  191,   81,  191,  191,  161,  212,
      215,  298,   35,  399,  298,  195,   82,  152,  195,  206,
      163,  164,  165,  196,   49,  168,   49,  197,  198,  199,
      197,  198,  199,   79,  183,  208,   80,  210,  209,  186,
      193,   81,  249,  300,  211,  161,  301,  398,  397,  194,
      181,  218,   82,  229,  233,  192,  222,  163,  164,  165,
      106,  233,  230,  234,  194,  210,  231,  410,  224,   37,

      234,  214,  211,  231,  231,   49,  233,  195,  206,   50,
      206,   41,   42,   43,  225,  234,  206,  227,  231,  197,
      198,  199,  251,   49,  236,  245,  241,  237,  396,  242,
      206,  206,  208,  229,  410,  209,  233,   49,   49,  298,
      106,  246,  395,  247,  206,  234,  208,  208,  220,  209,
      209,  244,  248,  291,  224,   49,  306,  288,  307,  302,
      236,   49,  243,  237,   79,  289,  275,   80,   85,  229,
      259,  301,  256,  261,  195,  276,  106,  234,  262,  394,
      206,  393,  108,   82,  232,  316,  197,  198,  199,  263,
      264,   37,  317,  392,  206,  109,  236,   49,  391,  237,

      206,  206,  264,   41,   42,   43,  266,   49,   49,  267,
      236,  275,  277,  237,  278,  298,  208,  208,  284,  209,
      209,  298,  268,  264,   37,  245,  314,  108,  390,  315,
       49,  304,  206,  285,  305,  410,   41,   42,   43,  266,
      109,  246,  267,  247,  206,  389,  298,  301,  236,  303,
      229,  237,  248,  301,  298,  269,  318,  106,  206,  319,
      236,  273,  312,  237,  313,  147,  206,  298,  298,  298,
      298,  358,  298,   49,  208,  280,  338,  209,  305,  275,
      275,  340,  208,  147,  284,  209,  301,  331,  332,  332,
      333,  311,  341,  388,  298,  108,  108,  206,  336,  301,

      301,  301,  301,  335,  334,  206,  298,  314,  109,  109,
      315,  316,  171,  236,  318,  312,  237,  319,  317,  344,
      173,  236,  298,  298,  237,  352,  301,  353,  298,  351,
      345,  298,  171,  338,  340,  352,  298,  298,  301,  344,
      147,  331,  171,  332,  298,  341,  354,  358,  355,  356,
      345,  280,  384,  298,  301,  301,  359,  301,  341,  367,
      301,  361,  298,  301,  365,  280,  366,  305,  301,  301,
      361,  298,  345,  374,  280,  368,  301,  210,  373,  298,
      369,  298,  383,  298,  211,  301,  385,  375,  386,  315,
      387,  370,  382,  319,  301,  317,  385,  386,  387,  315,

      316,  319,  371,  301,  317,  379,  400,  317,  378,  401,
      377,  301,  380,  301,  381,  301,  402,  376,  301,  403,
      301,  400,  301,  404,  401,  406,  404,  408,  305,  305,
      305,  398,  402,  406,  405,  403,  407,  405,  405,  409,
      371,  408,  409,  398,  407,  398,  398,  371,  359,  364,
      407,   44,   44,  322,  362,  359,   44,   44,   44,   44,
       50,   50,  342,  357,  350,   50,  349,   50,   50,   70,
      348,  347,  346,  320,   70,   70,   70,   78,   78,   84,
      171,  342,  309,  339,  337,  330,  329,   84,  114,  328,
      114,  114,  131,  327,  326,  325,  324,  131,  131,  131,

      134,  322,  322,  323,  322,  134,  134,  137,  321,  320,
      311,  309,  271,  308,  137,  137,  149,  307,  270,  268,
      149,  166,  297,  296,  295,  294,  293,  166,  166,  169,
      292,  290,  287,  286,  283,  282,  169,  169,  176,  281,
      280,  279,  273,  271,  270,  258,  176,  178,  257,  255,
      254,  178,  178,  200,  253,  252,  250,  240,  239,  200,
      200,  202,  238,  201,  232,  231,  223,  219,  216,  202,
      207,  177,  175,  205,  204,  207,  203,  207,  207,  226,
      226,  201,  192,  191,  226,  190,  226,  226,  235,  189,
      188,  185,  182,  180,  179,  235,  235,  260,  177,  177,

      175,  174,  260,  173,  141,  260,  265,  265,  172,  140,
      133,  265,  160,  265,  265,  272,  159,  157,  155,  154,
      272,  272,  299,  151,   88,  148,  115,   49,  145,  299,
      299,  310,  144,  141,  140,  139,  310,  310,  343,  138,
      133,  132,  129,  128,  126,  125,  343,  360,  124,  123,
      122,  121,   87,  120,  360,  360,  363,  119,  118,  117,
      363,  372,  116,  115,   49,  372,  372,   83,  113,  112,
      111,  110,  101,   99,   98,   97,   88,   96,   95,   94,
       93,   90,   89,   88,   87,   86,   85,   83,   75,   71,
       34,   68,   67,   66,   65,   64,   61,   60,   59,   47,

       34,  410,    3,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410
    } ;

static yyconst short int yy_chk[947] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   16,   16,   18,   18,   23,   35,   23,
       16,   24,   16,   28,   16,  437,   16,   16,   16,   21,
       21,   28,   24,   36,   62,   38,   21,   38,   41,   62,
       36,  432,   21,   21,   21,   21,   38,   41,   21,   99,
       41,   41,   70,   99,   57,   35,   35,   67,   42,   43,
       57,   21,   69,   67,   21,   22,   22,   42,   43,   69,

       42,   43,   22,   71,   38,   38,  106,  418,   22,   22,
       22,   22,   71,  417,   22,   40,   40,  106,   48,   70,
       70,   72,   40,   72,   40,   48,   40,  102,   40,   40,
       40,  115,   72,  121,   48,  111,   74,   48,  115,   77,
      119,  119,   48,   74,  131,   74,   77,   74,   77,  111,
       77,  105,  130,   48,  179,   77,  125,  125,  105,  130,
       72,   72,   75,   75,  102,  102,  121,  105,   77,   75,
      127,  127,  132,   75,  182,   75,   75,   75,  133,  132,
      105,  131,  131,  132,  135,  133,  140,  179,  136,  182,
      268,  137,  268,  185,  133,  135,  136,  140,  136,  138,

      136,  136,  136,  137,  137,  137,  138,  133,  154,  141,
      138,  146,  156,  170,  164,  138,  141,  185,  146,  180,
      170,  167,  165,  164,  163,  154,  164,  146,  138,  156,
      146,  165,  167,  163,  165,  146,  163,  163,  166,  212,
      180,  259,  411,  396,  260,  168,  146,  152,  169,  176,
      166,  166,  166,  168,  152,  168,  176,  168,  168,  168,
      169,  169,  169,  152,  183,  176,  152,  177,  176,  186,
      191,  152,  212,  259,  177,  192,  260,  395,  394,  191,
      152,  183,  152,  194,  198,  192,  186,  192,  192,  192,
      194,  197,  194,  198,  194,  210,  198,  183,  189,  189,

      197,  214,  210,  197,  197,  189,  199,  200,  202,  189,
      206,  189,  189,  189,  189,  199,  207,  189,  199,  200,
      200,  200,  214,  207,  202,  211,  206,  202,  393,  206,
      208,  209,  207,  229,  214,  207,  231,  208,  209,  261,
      229,  211,  392,  211,  235,  231,  208,  209,  220,  208,
      209,  209,  211,  250,  224,  220,  308,  248,  308,  261,
      235,  224,  208,  235,  220,  248,  234,  220,  250,  271,
      224,  261,  220,  224,  232,  234,  271,  234,  224,  391,
      236,  390,  234,  220,  232,  280,  232,  232,  232,  224,
      225,  225,  280,  389,  237,  234,  236,  225,  388,  236,

      243,  244,  264,  225,  225,  225,  225,  243,  244,  225,
      237,  275,  236,  237,  237,  263,  243,  244,  243,  243,
      244,  262,  225,  226,  226,  245,  279,  275,  384,  279,
      226,  263,  278,  244,  264,  264,  226,  226,  226,  226,
      275,  245,  226,  245,  277,  383,  298,  263,  278,  262,
      273,  278,  245,  262,  299,  226,  281,  273,  284,  281,
      277,  273,  277,  277,  278,  284,  285,  304,  301,  300,
      303,  358,  302,  285,  284,  358,  306,  284,  298,  309,
      311,  315,  285,  306,  285,  285,  299,  300,  301,  300,
      302,  311,  315,  382,  332,  309,  311,  313,  304,  304,

      301,  300,  303,  303,  302,  312,  353,  314,  309,  311,
      314,  316,  312,  313,  318,  313,  313,  318,  316,  319,
      329,  312,  333,  334,  312,  331,  332,  332,  335,  329,
      319,  336,  331,  338,  340,  352,  356,  354,  353,  344,
      338,  334,  352,  334,  355,  340,  333,  341,  335,  336,
      344,  341,  378,  366,  333,  334,  359,  331,  341,  356,
      335,  345,  365,  336,  354,  345,  355,  352,  356,  354,
      361,  367,  345,  366,  361,  359,  355,  371,  365,  373,
      359,  374,  377,  375,  371,  366,  379,  367,  380,  379,
      381,  359,  376,  381,  365,  380,  385,  386,  387,  385,

      398,  387,  372,  367,  386,  373,  397,  398,  370,  397,
      369,  373,  374,  374,  375,  375,  399,  368,  379,  399,
      380,  400,  381,  401,  400,  403,  404,  405,  385,  386,
      387,  405,  402,  406,  401,  402,  403,  404,  405,  407,
      363,  408,  409,  407,  406,  408,  409,  362,  360,  348,
      407,  412,  412,  347,  346,  343,  412,  412,  412,  412,
      413,  413,  342,  337,  326,  413,  325,  413,  413,  414,
      324,  323,  322,  321,  414,  414,  414,  415,  415,  416,
      320,  317,  310,  307,  305,  297,  296,  416,  419,  294,
      419,  419,  420,  293,  292,  291,  290,  420,  420,  420,

      421,  289,  288,  287,  286,  421,  421,  422,  283,  282,
      276,  274,  272,  270,  422,  422,  423,  269,  267,  266,
      423,  424,  257,  256,  254,  253,  252,  424,  424,  425,
      251,  249,  247,  246,  242,  241,  425,  425,  426,  240,
      239,  238,  230,  228,  227,  222,  426,  427,  221,  218,
      217,  427,  427,  428,  216,  215,  213,  205,  204,  428,
      428,  429,  203,  201,  196,  195,  187,  184,  181,  429,
      430,  178,  175,  174,  173,  430,  172,  430,  430,  431,
      431,  171,  162,  161,  431,  159,  431,  431,  433,  158,
      157,  155,  153,  151,  150,  433,  433,  434,  149,  148,

      147,  145,  434,  144,  143,  434,  435,  435,  142,  139,
      134,  435,  129,  435,  435,  436,  128,  126,  124,  123,
      436,  436,  438,  120,  118,  117,  116,  114,  113,  438,
      438,  439,  112,  110,  109,  108,  439,  439,  440,  107,
      104,  103,  101,  100,   98,   97,  440,  441,   96,   95,
       94,   93,   92,   91,  441,  441,  442,   90,   89,   88,
      442,  443,   86,   85,   84,  443,  443,   83,   82,   81,
       80,   79,   68,   66,   65,   64,   63,   61,   60,   59,
       58,   56,   55,   54,   53,   52,   51,   49,   39,   37,
       34,   33,   32,   31,   30,   29,   27,   26,   25,   20,

        6,    3,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "auto2.I"
#define INITIAL 0
#line 2 "auto2.I"
#include <stdlib.h>
#include <stdio.h> 
#include <stddef.h>
#include <conio.h>
#include <string.h> 
#include <stdbool.h>
#include <ctype.h>
#include "y.tab.h"

int num_lineas = 1, num_caracteres = 0; 
int contid=0, err=0;
const char *a[500];
FILE *fp;
int sw=0;
int swwhere=0;
#line 769 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 81 "auto2.I"


#line 923 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 411 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 903 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 83 "auto2.I"
{;} 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 84 "auto2.I"
{covertToUpper(yytext); return CREATE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 85 "auto2.I"
{covertToUpper(yytext); return SELECT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "auto2.I"
{covertToUpper(yytext); return FROM;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "auto2.I"
{covertToUpper(yytext); return DROP;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 88 "auto2.I"
{covertToUpper(yytext); return INSERT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "auto2.I"
{covertToUpper(yytext); return UPDATE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 90 "auto2.I"
{covertToUpper(yytext); return BORRAR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "auto2.I"
{covertToUpper(yytext); return VALUES;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "auto2.I"
{covertToUpper(yytext); swwhere=1; return WHERE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "auto2.I"
{covertToUpper(yytext); return ORDERBY;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "auto2.I"
{covertToUpper(yytext); return GROUPBY;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "auto2.I"
{covertToUpper(yytext); return ASCDESC;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 98 "auto2.I"
{ECHO; return PARAMETRO;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 99 "auto2.I"
{ECHO;printf(" "); return IDSORD;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 100 "auto2.I"
{ECHO;printf(" ");return IDS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "auto2.I"
{Id(a,contid,yytext);return ID;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "auto2.I"
{covertToUpper(yytext); return FUNCION;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "auto2.I"
{ECHO; char * found = strstr( yytext, "AND" ); 
						char * found1 = strstr( yytext, "OR" );
						char * found2 = strstr( yytext, "=" );
						char * found3 = strstr( yytext, ">" );
						char * found4 = strstr( yytext, "<" );
						if (found == NULL && found1 == NULL && found2 != NULL  && found3 == NULL && found4 == NULL && swwhere==0)                     
						{
  							return CONDICIONIGUAL;	
 	                                      
						}else{ return CONDICIONCOMPUESTA;}}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 117 "auto2.I"
{ECHO; char * found = strstr( yytext, "=" ); 
						char * found3 = strstr( yytext, ">" );
						char * found4 = strstr( yytext, "<" );
					if (found != NULL && found3 == NULL && found4 == NULL)                     
						{
  							return CONDICIONIGUAL;	
 	                                      
						}
						
						}					
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 128 "auto2.I"
{ECHO;return PARCRE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 130 "auto2.I"
{printf("\tERROR LEXICO = "); ECHO; printf("\t" );} 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 132 "auto2.I"
{printf("ENTERO=" ); ECHO; printf("\t");} 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 133 "auto2.I"
{printf("DECIMAL = " ); ECHO; printf("\t");} 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 134 "auto2.I"
{printf("COMILLA = " ); ECHO; printf("\t" );return COMILLA;} 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 135 "auto2.I"
{printf("IGUAL = " ); ECHO; printf("\t" ); return ERROR; } 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 136 "auto2.I"
{printf("PUNTO_COMA=" ); ECHO; printf("\t"); swwhere=0; return P_COMA;} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 137 "auto2.I"
{printf("DISTINTO_DE = " );ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 138 "auto2.I"
{printf("COMA=" );ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 139 "auto2.I"
{printf("PUNTO = " );ECHO; printf("\t"); return ERROR;} 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 140 "auto2.I"
{printf("MAYOR_IGUAL = " ); ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 141 "auto2.I"
{printf("MENOR_IGUAL = " ); ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 142 "auto2.I"
{printf("OPEN_PARENTESIS = " ); ECHO; printf("\t"); return P_ABRE;} 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 143 "auto2.I"
{printf("CLOSE_PARENTESIS = " ); ECHO; printf("\t");return P_CIERRA;} 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 144 "auto2.I"
{printf("MAYOR_QUE = " ); ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 145 "auto2.I"
{printf("MENOR_QUE = " ); ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 146 "auto2.I"
{printf("MAS = " ); ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 147 "auto2.I"
{printf("MENOS = " ); ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 148 "auto2.I"
{printf("ASTERISCO= " ); ECHO; printf("\t"); return ASTERICO;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 149 "auto2.I"
{printf("SLASH = " ); ECHO; printf("\t");return ERROR;} 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 150 "auto2.I"
{++num_lineas;int i=0;swwhere=0;} 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 151 "auto2.I"
{printf("\tERROR LEXICO = "); ECHO; printf("\t" ); return ERROR;} 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 152 "auto2.I"
ECHO;
	YY_BREAK
#line 1247 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 411 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 411 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 410);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 152 "auto2.I"



void Id(char *a[],int n, char* b){
	int i=0;
	for(i=0;i<n;i++){ 
	if(strcmp(a[i],b)==0){ break; }
	}
	
	if(i<n){
		printf("ID%d= ",i+1 ); ECHO; printf("\t");
	}
	else{
		printf(" ID%d= ",contid+1 ); ECHO; printf("\t");
		a[contid]=strdup(b); b=0; 
		contid=contid+1;
	}
}

void covertToUpper(char *str){
    char *newstr, *p;
    p = newstr = strdup(str);
    while(*p++=toupper(*p));
	printf(newstr);printf(" ");
    //return newstr;
}

int main(int argc,char *argv[]) 
{ 
char NomArch[100]; 
fp= fopen( "salida.txt", "w" );
printf("Ingrese nombre de archivo: " ); 
gets(NomArch); 
if ((yyin = fopen(NomArch, "rt" )) == NULL) 
{ 
printf("\nNo se puede abrir el archivo: %sn", NomArch); 
} 
else 
{ 
yyparse(); 
printf("\nLos IDs encontrados son: \n");
int i=0;
for(i=0;i<contid;i++){
	printf("\nID# %d = ",i+1);
	printf(a[i]);
	}	
printf("\nEl numero de lineas es: %d",num_lineas);
} 
if(sw==0)
{
	fprintf(fp,"CORRECTO");
}
fclose(yyin); 
getch(); 
return 0; 
}


int yyerror(void)
{
	if(sw==0)
	{
		fprintf(fp,"incorrecto\n\n");
		sw=1;
	}
	if(yylineno > err){
		printf("Error en linea: %d ",yylineno);
		fprintf(fp,"Error en linea: %d\n",yylineno);
		err= yylineno;
	}

yyparse();

}

int yywrap(void)
{
return 1;
}

